#!/usr/bin/env cwl-runner
#
# using dockerized version of assign_taxon.py 
# assign_taxon.py -t database_taxonomy.tsv -o outlier.txt -out consensus_taxonomy.txt
# parameters:
#       -o outlier.txt -- [input] outliers, generated by outliers.cwl step
#       -t database_taxonomy.tsv -- [input] constant, taxonomy info related to a BLAST DB
#       -out consensus_taxonomy.txt -- [output] - actual program output
cwlVersion: v1.0
class: CommandLineTool
baseCommand: assign_taxon.py
hints:
  DockerRequirement:
    dockerPull: ncbi/outlier-hit-detection
inputs:
  t_flag:
    type: File?
    inputBinding:
        position: 1
        prefix: -t
  o_flag:
    type: File?
    inputBinding:
        position: 2
        prefix: -o
  out_flag:
    type: string
    inputBinding:
        position: 3
        prefix: -out

outputs:
  assign_taxon_results:
     type: File
     outputBinding:
        glob: $(inputs.out_flag) 

